BEGIN {
  n = 0;
  FS = "[ \t,]*";
  print "// File is generated by script."
}



/^[ \t]*\/\/.*$/ {
  # comment ignore
  next;
}



/^%begin_c/ {
  in_c_mode = 1;
  next;
}



/^%end_c/ {
  in_c_mode = 0;
  next;
}



/^[ \t]*$/ {
  next;
}




{
  sub("//.*", "");
  if (!in_c_mode) {
    for (i = 1; i <= NF; ++i) {
      if (!($i ~ /^[ \t]*$/)) {
        if (1 == i) {
          printf("ENUM(%s, %d", $i, n);
        } else if (2 == i) {
          printf(", %s", $i);
        } else {
          printf(" | %s", $i);
        }
      }
    }
    printf("),\n");
  } else {
    print $0;
  }
  next;
}
